spring:
  kafka:
    bootstrap-servers: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
    consumer:
      group-id: ces-consumer-group-prod
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.ces.infrastructure.kafka.FeedMessageDeserializer

ces:
  kafka:
    topics:
      - prod-customer-events
      - prod-order-events
      - prod-notification-events
  websocket:
    base-url: wss://ces.example.com/ws
