spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.ces.infrastructure.kafka.FeedMessageDeserializer

ces:
  kafka:
    topics:
      - dev-customer-events
      - dev-order-events
      - dev-notification-events
  websocket:
    base-url: ws://localhost:8080/ws
